import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { automationTechnologies } from "./portfolio/automatizaciones/data";
import { ArrowUpRight, ArrowRight, Check, Code2, Workflow, Radar, Layers, Search, Plus, ShieldCheck, Zap } from "lucide-react";
import { ContactOptions } from "./contact-options";
import styles from "./navy.module.css";

const whatsappUrl = "https://wa.me/5491168905153?text=" + encodeURIComponent("Hola Navy Labs, quiero contarles mi proyecto.");

export const metadata: Metadata = { title: "Navy Labs — Tecnología con foco en ventas", description: "Webs, SEO, Ads, automatizaciones y apps inteligentes. Convertimos problemas de negocio en soluciones digitales claras." };

const services = [
  { icon: Code2, title: "Webs y landings", subtitle: "Diseñadas para convertir.", text: "Una web rápida, clara y pensada para que tus visitas den el siguiente paso. Desde una landing hasta tu sitio completo.", tags: "Diseño UX/UI · Desarrollo · Analítica" },
  { icon: Search, title: "SEO & Ads", subtitle: "Que te encuentren los correctos.", text: "Conectamos tu propuesta con personas que la necesitan. Tráfico orgánico y campañas con objetivos y medición claros.", tags: "SEO técnico · Google Ads · Meta Ads" },
  { icon: Workflow, title: "Automatizaciones & CRM", subtitle: "Menos tareas. Más negocio.", text: "Conectamos tus herramientas, ordenamos tus contactos y automatizamos el seguimiento para que ninguna oportunidad se pierda.", tags: "Integraciones · CRM · Workflows" },
  { icon: Radar, title: "Apps inteligentes", subtitle: "Ideas que hacen cosas reales.", text: "IA para asistir a tu equipo e IoT para conectar el mundo físico. Construimos un primer producto útil y validamos antes de escalar.", tags: "IA aplicada · IoT · MVPs" },
  { icon: Layers, title: "Ingeniería de datos a medida", subtitle: "Datos claros. Decisiones mejores.", text: "Conectamos tus fuentes, automatizamos pipelines y diseñamos dashboards para transformar datos dispersos en información útil para tu negocio.", tags: "Arquitectura · ETL/ELT · Dashboards" },
];
const faqs = [
  ["¿Cuánto tarda un proyecto?", "Una landing suele requerir entre 2 y 4 semanas, según alcance, contenido e integraciones. Una app requiere una estimación propia. Antes de empezar acordamos entregables y un calendario realista."],
  ["¿La web y el código son míos?", "Sí. La propuesta contempla la entrega del código desarrollado, accesos y documentación tras el pago acordado. Las licencias de terceros se detallan por separado. Tus cuentas y tu dominio quedan a tu nombre."],
  ["¿Ofrecen mantenimiento después del lanzamiento?", "Sí, como servicio opcional con alcance y precio definidos. Podemos cubrir actualizaciones, monitoreo y mejoras. También entregamos documentación para que puedas trabajar con otro equipo."],
  ["¿Necesito tener los textos y las imágenes?", "Podés traerlos o podemos incluir su creación en la propuesta. Primero definimos tu oferta, público y objetivos. Los recursos y licencias que hagan falta se acuerdan antes de comenzar."],
  ["¿Cómo sé cuánto va a costar?", "Después de una primera conversación recibís una propuesta con alcance, etapas, inversión y costos de herramientas. Si algo queda fuera del alcance, se cotiza antes de hacerlo."],
];

function Brand() { return <span className={styles.brand}>navy<span className={styles.brandMark}>↗</span><span className={styles.brandLabs}>labs</span></span>; }
function Heading({ label, title, text }: { label: string; title: string; text?: string }) { return <div className={styles.sectionHeading}><span className={styles.eyebrow}>{label}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>; }

export default function NavyLabsPage() {
  return <div className={styles.site}>
    <a className={styles.skip} href="#contenido">Saltar al contenido</a>
    <header className={styles.header}><a href="#" aria-label="Navy Labs, inicio"><Brand /></a><nav aria-label="Navegación principal"><a href="#servicios">Qué hacemos</a><a href="#proceso">Cómo trabajamos</a><a href="#faq">FAQ</a></nav><a className={styles.headerCta} href={whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label="Hablar con especialista por WhatsApp (abre en otra pestaña)">Hablar con especialista <ArrowUpRight size={16}/></a></header>
    <main id="contenido">
      <section className={styles.hero}>
        <div className={styles.heroCopy}><span className={styles.eyebrow}><span className={styles.dot}/> TU PRÓXIMO PASO DIGITAL</span><h1>Construimos lo que<br/>tu negocio necesita<br/><span>para crecer.</span></h1><p className={styles.heroLead}>Creación de páginas web, automatizaciones y tecnología <strong>con foco en ventas.</strong></p><p className={styles.heroText}>Unimos estrategia, diseño y desarrollo para ayudarte a atraer clientes, simplificar procesos y crecer con mejores herramientas.</p><div className={styles.actions}><a className={styles.primary} href="#contacto">Hablemos de tu proyecto <ArrowUpRight size={18}/></a><a className={styles.secondary} href="#servicios">Explorar servicios <ArrowRight size={17}/></a></div><div className={styles.trust}><span><Check size={14}/> Alcance y costos claros</span><span><Check size={14}/> Tu código, tus cuentas</span></div></div>
        <div className={styles.heroVisual} aria-label="Ilustración de un sistema que conecta atracción, conversión y automatización">
          <div className={styles.visualTop}><span>NAVY LABS / SYSTEM VIEW</span><span className={styles.live}><span className={styles.dot}/> CONECTADO</span></div>
          <div className={styles.orbit}><div className={styles.orbitInner}/><div className={styles.orbitCore}><span>n↗</span><small>IDEA → IMPACTO</small></div><div className={`${styles.node} ${styles.nodeOne}`}><Search size={19}/><div><small>01 / ATRAER</small><strong>El tráfico correcto</strong></div></div><div className={`${styles.node} ${styles.nodeTwo}`}><Code2 size={19}/><div><small>02 / CONVERTIR</small><strong>Una mejor experiencia</strong></div></div><div className={`${styles.node} ${styles.nodeThree}`}><Workflow size={19}/><div><small>03 / ESCALAR</small><strong>Procesos conectados</strong></div></div></div>
          <div className={styles.visualBottom}><span>ESTRATEGIA + DISEÑO + TECNOLOGÍA</span><ArrowUpRight size={20}/></div>
        </div>
      </section>
      <div className={styles.principles}><span>BUENAS BASES. MEJORES POSIBILIDADES.</span><span><Zap size={17}/> Velocidad por diseño</span><span><ShieldCheck size={17}/> Control e independencia</span><span><Layers size={17}/> Preparado para crecer</span></div>
      <section id="servicios" className={styles.section}><div className={styles.headingRow}><Heading label="01 / QUÉ HACEMOS" title="Lo que necesitás para avanzar." text="Cinco formas de resolver el próximo desafío de tu negocio."/><a href="#contacto" className={styles.textLink}>Encontrá tu solución <ArrowUpRight size={18}/></a></div><div className={styles.services}>{services.map(({icon: Icon, title, subtitle, text, tags}, i) => <article className={styles.service} key={title}><div className={styles.cardTop}><Icon size={25} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{i < 5 ? <Link href={i === 0 ? "/portfolio/webs" : i === 1 ? "/portfolio/seo" : i === 2 ? "/portfolio/automatizaciones" : i === 3 ? "/portfolio/apps" : "/portfolio/datos"}>{title}</Link> : title}</h3><strong>{subtitle}</strong><p>{text}</p>{i === 2 && <div className={styles.automationLogos} aria-label="Make, n8n, HubSpot, Salesforce y Perfit">{automationTechnologies.map(tool => <Image key={tool.name} src={`/technologies/${tool.logo}`} alt={tool.name} title={tool.name} width={30} height={26}/>)}</div>}<div className={styles.cardBottom}><small>{tags}</small><Link href={i === 0 ? "/portfolio/webs" : i === 1 ? "/portfolio/seo" : i === 2 ? "/portfolio/automatizaciones" : i === 3 ? "/portfolio/apps" : "/portfolio/datos"} aria-label={i < 5 ? `Ver portfolio de ${title}` : `Consultar sobre ${title}`}><ArrowUpRight size={20}/></Link></div></article>)}<article className={styles.serviceCta}><span className={styles.eyebrow}>EMPECEMOS POR EL PROBLEMA</span><h3>¿No sabés qué<br/>necesitás todavía?</h3><p>Contanos qué querés mejorar. Te ayudamos a definir el primer paso.</p><a href="#contacto">Pensemos juntos <ArrowUpRight size={20}/></a></article></div></section>
      <section id="proceso" className={`${styles.section} ${styles.process}`}><Heading label="02 / CÓMO TRABAJAMOS" title="Un proceso claro. De principio a fin."/><div className={styles.steps}>{[["01", "Entendemos", "Tu negocio, tus clientes y el problema que vale la pena resolver."], ["02", "Definimos", "Una propuesta con entregables, inversión y tiempos. Sin letra chica."], ["03", "Construimos", "Diseño y desarrollo por etapas, con avances que podés revisar."], ["04", "Lanzamos", "Medimos, documentamos y te entregamos las llaves de tu proyecto."]].map(([n,t,d])=><article key={n}><span>{n} <ArrowRight size={18}/></span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
      <section className={`${styles.section} ${styles.stack}`}><Heading label="03 / LA TECNOLOGÍA, A TU FAVOR" title="Tecnología que queda en tus manos." text="Elegimos las herramientas según tu proyecto, no al revés."/><p className={styles.ownershipText}>Sin plataformas cerradas ni dependencias innecesarias.</p><div className={styles.technicalBacking} aria-label="Respaldo técnico: Next.js, Supabase, Tailwind CSS, Cloudflare y OpenAI">{[["nextjs.svg", "Next.js"],["supabase.svg", "Supabase"],["tailwindcss.svg", "Tailwind CSS"],["cloudflare.svg", "Cloudflare"],["openai.svg", "OpenAI"]].map(([logo,name])=><Image key={name} src={`/technologies/${logo}`} alt={`Logo de ${name}`} title={name} width={24} height={24}/>)}</div></section>
      <section id="faq" className={`${styles.section} ${styles.faq}`}><Heading label="04 / SIN DUDAS PENDIENTES" title="Hablemos claro." text="Las respuestas que necesitás antes de dar el siguiente paso."/><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></section>
      <section id="contacto" className={`${styles.section} ${styles.contact}`}><div><span className={styles.eyebrow}>05 / HAGAMOS QUE PASE</span><h2>Tu próxima<br/>gran versión<br/><span>empieza acá.</span></h2><p>Contanos dónde estás y a dónde querés llegar. Te respondemos en menos de 24 horas hábiles para coordinar una primera conversación.</p><div className={styles.contactBenefits}><span><Check size={17}/> Primera conversación sin costo</span><span><Check size={17}/> Propuesta a medida, sin compromiso</span><span><Check size={17}/> Contacto directo con el equipo</span></div></div><ContactOptions/></section>
    </main>
    <footer className={styles.footer}><div><a href="#" aria-label="Navy Labs, inicio"><Brand/></a><p>Estrategia y tecnología para el próximo paso.</p></div><div className={styles.footerLinks}><a href="#servicios">Servicios</a><a href="#contacto">Contacto</a><a href="mailto:hola@navylabs.tech">hola@navylabs.tech</a><a href="/privacidad">Privacidad</a><a href="/terminos">Términos</a></div><div className={styles.copyright}><span>© {new Date().getFullYear()} Navy Labs</span><span>HECHO CON INTENCIÓN. CONSTRUIDO PARA CRECER. ↗</span></div></footer>
  </div>;
}
